// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNnJWkUGYMQDYQ1QQWmRWBIPFtVjIu9Q',
    appId: '1:1081443534195:web:728109a411a546da543106',
    messagingSenderId: '1081443534195',
    projectId: 'my-daily-todo-app',
    authDomain: 'my-daily-todo-app.firebaseapp.com',
    storageBucket: 'my-daily-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ckdSMP_ySZ0LRdLWkxd5Px0los_w718',
    appId: '1:1081443534195:android:b6eaf177e379fdac543106',
    messagingSenderId: '1081443534195',
    projectId: 'my-daily-todo-app',
    storageBucket: 'my-daily-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjCDe_OuQ5o4BLTwAJw7SIZmeECORmSUs',
    appId: '1:1081443534195:ios:995f034e5a4f8abf543106',
    messagingSenderId: '1081443534195',
    projectId: 'my-daily-todo-app',
    storageBucket: 'my-daily-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjCDe_OuQ5o4BLTwAJw7SIZmeECORmSUs',
    appId: '1:1081443534195:ios:995f034e5a4f8abf543106',
    messagingSenderId: '1081443534195',
    projectId: 'my-daily-todo-app',
    storageBucket: 'my-daily-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnNnJWkUGYMQDYQ1QQWmRWBIPFtVjIu9Q',
    appId: '1:1081443534195:web:7aee0a9e62568cf2543106',
    messagingSenderId: '1081443534195',
    projectId: 'my-daily-todo-app',
    authDomain: 'my-daily-todo-app.firebaseapp.com',
    storageBucket: 'my-daily-todo-app.firebasestorage.app',
  );
}
